# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Help_Window(object):
    def setupUi(self, Help_Window):
        Help_Window.setObjectName("Help_Window")
        Help_Window.resize(573, 457)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        Help_Window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../image/1200px-Athens_Metro_Logo.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Help_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Help_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 501, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.pasos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.pasos.setContentsMargins(0, 0, 0, 0)
        self.pasos.setObjectName("pasos")
        self.HelpWindow = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.HelpWindow.setFont(font)
        self.HelpWindow.setObjectName("HelpWindow")
        self.pasos.addWidget(self.HelpWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.paso_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_1.setFont(font)
        self.paso_1.setObjectName("paso_1")
        self.verticalLayout.addWidget(self.paso_1)
        self.paso_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_2.setFont(font)
        self.paso_2.setObjectName("paso_2")
        self.verticalLayout.addWidget(self.paso_2)
        self.paso_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_3.setFont(font)
        self.paso_3.setObjectName("paso_3")
        self.verticalLayout.addWidget(self.paso_3)
        self.paso_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_4.setFont(font)
        self.paso_4.setObjectName("paso_4")
        self.verticalLayout.addWidget(self.paso_4)
        self.paso_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_5.setFont(font)
        self.paso_5.setObjectName("paso_5")
        self.verticalLayout.addWidget(self.paso_5)
        self.paso_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_6.setFont(font)
        self.paso_6.setObjectName("paso_6")
        self.verticalLayout.addWidget(self.paso_6)
        self.paso_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.paso_7.setFont(font)
        self.paso_7.setObjectName("paso_7")
        self.verticalLayout.addWidget(self.paso_7)
        self.pasos.addLayout(self.verticalLayout)
        Help_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Help_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.menubar.setObjectName("menubar")
        Help_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Help_Window)
        self.statusbar.setObjectName("statusbar")
        Help_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Help_Window)
        QtCore.QMetaObject.connectSlotsByName(Help_Window)

    def retranslateUi(self, Help_Window):
        _translate = QtCore.QCoreApplication.translate
        Help_Window.setWindowTitle(_translate("Help_Window", "Help"))
        self.HelpWindow.setText(_translate("Help_Window", "Pasos:"))
        self.paso_1.setText(_translate("Help_Window", "1. Aaron compila"))
        self.paso_2.setText(_translate("Help_Window", "2. Aaron ejecuta"))
        self.paso_3.setText(_translate("Help_Window", "3. Aaron la lia"))
        self.paso_4.setText(_translate("Help_Window", "4. Aaron hace push"))
        self.paso_5.setText(_translate("Help_Window", "5. Aaron la lia en git"))
        self.paso_6.setText(_translate("Help_Window", "6. Aaron lia el proyecyo"))
        self.paso_7.setText(_translate("Help_Window", "7. Aaron es un liante"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help_Window = QtWidgets.QMainWindow()
    ui = Ui_Help_Window()
    ui.setupUi(Help_Window)
    Help_Window.show()
    sys.exit(app.exec_())

