# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_minimalista.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1412, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1412, 843))
        MainWindow.setMaximumSize(QtCore.QSize(1412, 843))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../image/1200px-Athens_Metro_Logo.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.image_container = QtWidgets.QFrame(self.centralwidget)
        self.image_container.setGeometry(QtCore.QRect(0, 0, 1081, 831))
        self.image_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_container.setLineWidth(20)
        self.image_container.setMidLineWidth(20)
        self.image_container.setObjectName("image_container")
        self.map_image = QtWidgets.QLabel(self.image_container)
        self.map_image.setGeometry(QtCore.QRect(0, 0, 1071, 821))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        self.map_image.setFont(font)
        self.map_image.setStyleSheet("background-color: rgb(205, 236, 255);")
        self.map_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.map_image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.map_image.setText("")
        self.map_image.setPixmap(QtGui.QPixmap("../../../image/mapa_metro_atenasCHULO.jpg"))
        self.map_image.setScaledContents(True)
        self.map_image.setWordWrap(True)
        self.map_image.setObjectName("map_image")
        self.selection_container = QtWidgets.QFrame(self.image_container)
        self.selection_container.setGeometry(QtCore.QRect(740, 0, 301, 181))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.selection_container.setFont(font)
        self.selection_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selection_container.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selection_container.setObjectName("selection_container")
        self.origin_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.origin_comboBox.setGeometry(QtCore.QRect(90, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        self.origin_comboBox.setFont(font)
        self.origin_comboBox.setObjectName("origin_comboBox")
        self.destiny_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.destiny_comboBox.setGeometry(QtCore.QRect(90, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        self.destiny_comboBox.setFont(font)
        self.destiny_comboBox.setCurrentText("")
        self.destiny_comboBox.setObjectName("destiny_comboBox")
        self.destiny_icon = QtWidgets.QLabel(self.selection_container)
        self.destiny_icon.setGeometry(QtCore.QRect(10, 120, 61, 61))
        self.destiny_icon.setText("")
        self.destiny_icon.setPixmap(QtGui.QPixmap("../../../image/flag-color.png"))
        self.destiny_icon.setScaledContents(True)
        self.destiny_icon.setObjectName("destiny_icon")
        self.origin_icon = QtWidgets.QLabel(self.selection_container)
        self.origin_icon.setGeometry(QtCore.QRect(10, 30, 61, 61))
        self.origin_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.origin_icon.setText("")
        self.origin_icon.setPixmap(QtGui.QPixmap("../../../image/mapa-color.png"))
        self.origin_icon.setScaledContents(True)
        self.origin_icon.setObjectName("origin_icon")
        self.stations_list = QtWidgets.QListView(self.centralwidget)
        self.stations_list.setGeometry(QtCore.QRect(1070, 240, 341, 581))
        self.stations_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stations_list.setObjectName("stations_list")
        self.results_container = QtWidgets.QFrame(self.centralwidget)
        self.results_container.setGeometry(QtCore.QRect(1070, 0, 341, 241))
        self.results_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_container.setObjectName("results_container")
        self.background_list = QtWidgets.QListView(self.results_container)
        self.background_list.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.background_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_list.setObjectName("background_list")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.results_container)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 301, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        self.stations = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.stations.setFont(font)
        self.stations.setObjectName("stations")
        self.verticalLayout.addWidget(self.stations)
        self.distances = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.distances.setFont(font)
        self.distances.setObjectName("distances")
        self.verticalLayout.addWidget(self.distances)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.time_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.time_value.setFont(font)
        self.time_value.setText("")
        self.time_value.setObjectName("time_value")
        self.verticalLayout_2.addWidget(self.time_value)
        self.stations_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.stations_value.setFont(font)
        self.stations_value.setToolTipDuration(-2)
        self.stations_value.setText("")
        self.stations_value.setObjectName("stations_value")
        self.verticalLayout_2.addWidget(self.stations_value)
        self.distances_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.distances_value.setFont(font)
        self.distances_value.setText("")
        self.distances_value.setObjectName("distances_value")
        self.verticalLayout_2.addWidget(self.distances_value)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.results_container.raise_()
        self.image_container.raise_()
        self.stations_list.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1412, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.actionHelp.setFont(font)
        self.actionHelp.setShortcut("")
        self.actionHelp.setObjectName("actionHelp")
        self.action = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.action.setFont(font)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metro Atenas"))
        self.time.setText(_translate("MainWindow", "Tiempo:"))
        self.stations.setText(_translate("MainWindow", "Estaciones:"))
        self.distances.setText(_translate("MainWindow", "Distancias:"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.action.setText(_translate("MainWindow", "Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

