# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_minimalista.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1409, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../image/1200px-Athens_Metro_Logo.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.image_container = QtWidgets.QFrame(self.centralwidget)
        self.image_container.setGeometry(QtCore.QRect(0, 0, 1081, 831))
        self.image_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_container.setLineWidth(20)
        self.image_container.setMidLineWidth(20)
        self.image_container.setObjectName("image_container")
        self.map_image = QtWidgets.QLabel(self.image_container)
        self.map_image.setGeometry(QtCore.QRect(0, 0, 1071, 821))
        self.map_image.setStyleSheet("background-color: rgb(205, 236, 255);")
        self.map_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.map_image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.map_image.setText("")
        self.map_image.setPixmap(QtGui.QPixmap("../../../image/mapa_metro_atenasCHULO.jpg"))
        self.map_image.setScaledContents(True)
        self.map_image.setWordWrap(True)
        self.map_image.setObjectName("map_image")
        self.selection_container = QtWidgets.QFrame(self.image_container)
        self.selection_container.setGeometry(QtCore.QRect(740, 30, 281, 181))
        self.selection_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selection_container.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selection_container.setObjectName("selection_container")
        self.origin_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.origin_comboBox.setGeometry(QtCore.QRect(90, 60, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.origin_comboBox.setFont(font)
        self.origin_comboBox.setObjectName("origin_comboBox")
        self.origin_comboBox.addItem("")
        self.origin_comboBox.addItem("")
        self.destiny_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.destiny_comboBox.setGeometry(QtCore.QRect(90, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.destiny_comboBox.setFont(font)
        self.destiny_comboBox.setObjectName("destiny_comboBox")
        self.destiny_comboBox.addItem("")
        self.destiny_comboBox.addItem("")
        self.destiny_icon = QtWidgets.QLabel(self.selection_container)
        self.destiny_icon.setGeometry(QtCore.QRect(10, 120, 61, 61))
        self.destiny_icon.setText("")
        self.destiny_icon.setPixmap(QtGui.QPixmap("../../../image/flag-color.png"))
        self.destiny_icon.setScaledContents(True)
        self.destiny_icon.setObjectName("destiny_icon")
        self.origin_icon = QtWidgets.QLabel(self.selection_container)
        self.origin_icon.setGeometry(QtCore.QRect(10, 30, 61, 61))
        self.origin_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.origin_icon.setText("")
        self.origin_icon.setPixmap(QtGui.QPixmap("../../../image/mapa-color.png"))
        self.origin_icon.setScaledContents(True)
        self.origin_icon.setObjectName("origin_icon")
        self.stations_list = QtWidgets.QListView(self.centralwidget)
        self.stations_list.setGeometry(QtCore.QRect(1070, 240, 341, 591))
        self.stations_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stations_list.setObjectName("stations_list")
        self.results_container = QtWidgets.QFrame(self.centralwidget)
        self.results_container.setGeometry(QtCore.QRect(1070, 0, 341, 241))
        self.results_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_container.setObjectName("results_container")
        self.time = QtWidgets.QLabel(self.results_container)
        self.time.setGeometry(QtCore.QRect(30, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.distances = QtWidgets.QLabel(self.results_container)
        self.distances.setGeometry(QtCore.QRect(30, 60, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        self.distances.setFont(font)
        self.distances.setObjectName("distances")
        self.stations = QtWidgets.QLabel(self.results_container)
        self.stations.setGeometry(QtCore.QRect(30, 150, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        self.stations.setFont(font)
        self.stations.setObjectName("stations")
        self.background_list = QtWidgets.QListView(self.results_container)
        self.background_list.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.background_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_list.setObjectName("background_list")
        self.background_list.raise_()
        self.time.raise_()
        self.distances.raise_()
        self.stations.raise_()
        self.results_container.raise_()
        self.image_container.raise_()
        self.stations_list.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.origin_comboBox.setItemText(0, _translate("MainWindow", "Seleccione Origen"))
        self.origin_comboBox.setItemText(1, _translate("MainWindow", "A"))
        self.destiny_comboBox.setCurrentText(_translate("MainWindow", "Seleccione Destino"))
        self.destiny_comboBox.setItemText(0, _translate("MainWindow", "Seleccione Destino"))
        self.destiny_comboBox.setItemText(1, _translate("MainWindow", "B"))
        self.time.setText(_translate("MainWindow", "Tiempo:"))
        self.distances.setText(_translate("MainWindow", "Distancias:"))
        self.stations.setText(_translate("MainWindow", "Estaciones:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

