from PyQt5 import QtCore, QtGui, QtWidgets
from util import resource_path


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1412, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1412, 843))
        MainWindow.setMaximumSize(QtCore.QSize(1412, 843))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(resource_path("image/1200px-Athens_Metro_Logo.svg.png")),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.image_container = QtWidgets.QFrame(self.centralwidget)
        self.image_container.setGeometry(QtCore.QRect(0, 0, 1081, 831))
        self.image_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_container.setLineWidth(20)
        self.image_container.setMidLineWidth(20)
        self.image_container.setObjectName("image_container")
        self.map_image = QtWidgets.QLabel(self.image_container)
        self.map_image.setGeometry(QtCore.QRect(0, 0, 1071, 821))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        self.map_image.setFont(font)
        self.map_image.setStyleSheet("background-color: rgb(205, 236, 255);")
        self.map_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.map_image.setFrameShadow(QtWidgets.QFrame.Plain)
        self.map_image.setText("")
        self.map_image.setPixmap(
            QtGui.QPixmap(resource_path("image/mapa_metro_atenasCHULO.jpg")))
        self.map_image.setScaledContents(True)
        self.map_image.setWordWrap(True)
        self.map_image.setObjectName("map_image")

        self.frame_paradas = QtWidgets.QFrame(self.image_container)
        self.frame_paradas.setGeometry(QtCore.QRect(-61, 4, 1131, 791))
        self.frame_paradas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paradas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paradas.setObjectName("frame_paradas")
        self.i_Victoria = QtWidgets.QLabel(self.frame_paradas)
        self.i_Victoria.setGeometry(QtCore.QRect(410, 440, 11, 11))
        self.i_Victoria.setText("")
        self.i_Victoria.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Victoria.setScaledContents(True)
        self.i_Victoria.setObjectName("i_Victoria")
        self.i_Tavros = QtWidgets.QLabel(self.frame_paradas)
        self.i_Tavros.setGeometry(QtCore.QRect(315, 599, 11, 11))
        self.i_Tavros.setText("")
        self.i_Tavros.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Tavros.setScaledContents(True)
        self.i_Tavros.setObjectName("i_Tavros")
        self.i_Metaxourghio = QtWidgets.QLabel(self.frame_paradas)
        self.i_Metaxourghio.setGeometry(QtCore.QRect(379, 478, 11, 11))
        self.i_Metaxourghio.setText("")
        self.i_Metaxourghio.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Metaxourghio.setScaledContents(True)
        self.i_Metaxourghio.setObjectName("i_Metaxourghio")
        self.i_Syngrou_Fix = QtWidgets.QLabel(self.frame_paradas)
        self.i_Syngrou_Fix.setGeometry(QtCore.QRect(395, 594, 11, 11))
        self.i_Syngrou_Fix.setText("")
        self.i_Syngrou_Fix.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Syngrou_Fix.setScaledContents(True)
        self.i_Syngrou_Fix.setObjectName("i_Syngrou_Fix")
        self.i_Akropoli = QtWidgets.QLabel(self.frame_paradas)
        self.i_Akropoli.setGeometry(QtCore.QRect(411, 568, 11, 11))
        self.i_Akropoli.setText("")
        self.i_Akropoli.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Akropoli.setScaledContents(True)
        self.i_Akropoli.setObjectName("i_Akropoli")
        self.i_Aghios_Antonios = QtWidgets.QLabel(self.frame_paradas)
        self.i_Aghios_Antonios.setGeometry(QtCore.QRect(299, 367, 11, 11))
        self.i_Aghios_Antonios.setText("")
        self.i_Aghios_Antonios.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Aghios_Antonios.setScaledContents(True)
        self.i_Aghios_Antonios.setObjectName("i_Aghios_Antonios")
        self.i_Halandri = QtWidgets.QLabel(self.frame_paradas)
        self.i_Halandri.setGeometry(QtCore.QRect(739, 294, 11, 11))
        self.i_Halandri.setText("")
        self.i_Halandri.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Halandri.setScaledContents(True)
        self.i_Halandri.setObjectName("i_Halandri")
        self.i_Aghios_Nikolaos = QtWidgets.QLabel(self.frame_paradas)
        self.i_Aghios_Nikolaos.setGeometry(QtCore.QRect(398, 368, 11, 11))
        self.i_Aghios_Nikolaos.setText("")
        self.i_Aghios_Nikolaos.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Aghios_Nikolaos.setScaledContents(True)
        self.i_Aghios_Nikolaos.setObjectName("i_Aghios_Nikolaos")
        self.i_Thissio = QtWidgets.QLabel(self.frame_paradas)
        self.i_Thissio.setGeometry(QtCore.QRect(374, 533, 11, 11))
        self.i_Thissio.setText("")
        self.i_Thissio.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Thissio.setScaledContents(True)
        self.i_Thissio.setObjectName("i_Thissio")
        self.i_KAT = QtWidgets.QLabel(self.frame_paradas)
        self.i_KAT.setGeometry(QtCore.QRect(683, 59, 11, 11))
        self.i_KAT.setText("")
        self.i_KAT.setPixmap(QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_KAT.setScaledContents(True)
        self.i_KAT.setObjectName("i_KAT")
        self.i_Kallithea = QtWidgets.QLabel(self.frame_paradas)
        self.i_Kallithea.setGeometry(QtCore.QRect(291, 613, 11, 11))
        self.i_Kallithea.setText("")
        self.i_Kallithea.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Kallithea.setScaledContents(True)
        self.i_Kallithea.setObjectName("i_Kallithea")
        self.i_Sepolia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Sepolia.setGeometry(QtCore.QRect(351, 390, 11, 11))
        self.i_Sepolia.setText("")
        self.i_Sepolia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Sepolia.setScaledContents(True)
        self.i_Sepolia.setObjectName("i_Sepolia")
        self.i_Ano_Patissia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Ano_Patissia.setGeometry(QtCore.QRect(436, 276, 11, 11))
        self.i_Ano_Patissia.setText("")
        self.i_Ano_Patissia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Ano_Patissia.setScaledContents(True)
        self.i_Ano_Patissia.setObjectName("i_Ano_Patissia")
        self.i_Doukissis_Plakentias = QtWidgets.QLabel(self.frame_paradas)
        self.i_Doukissis_Plakentias.setGeometry(QtCore.QRect(782, 286, 11, 11))
        self.i_Doukissis_Plakentias.setText("")
        self.i_Doukissis_Plakentias.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Doukissis_Plakentias.setScaledContents(True)
        self.i_Doukissis_Plakentias.setObjectName("i_Doukissis_Plakentias")
        self.i_Neos_Kosmos = QtWidgets.QLabel(self.frame_paradas)
        self.i_Neos_Kosmos.setGeometry(QtCore.QRect(403, 627, 11, 11))
        self.i_Neos_Kosmos.setText("")
        self.i_Neos_Kosmos.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Neos_Kosmos.setScaledContents(True)
        self.i_Neos_Kosmos.setObjectName("i_Neos_Kosmos")
        self.i_Iraklio = QtWidgets.QLabel(self.frame_paradas)
        self.i_Iraklio.setGeometry(QtCore.QRect(546, 162, 11, 11))
        self.i_Iraklio.setText("")
        self.i_Iraklio.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Iraklio.setScaledContents(True)
        self.i_Iraklio.setObjectName("i_Iraklio")
        self.i_Monastiraki = QtWidgets.QLabel(self.frame_paradas)
        self.i_Monastiraki.setGeometry(QtCore.QRect(397, 527, 11, 11))
        self.i_Monastiraki.setText("")
        self.i_Monastiraki.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Monastiraki.setScaledContents(True)
        self.i_Monastiraki.setObjectName("i_Monastiraki")
        self.i_Perissos = QtWidgets.QLabel(self.frame_paradas)
        self.i_Perissos.setGeometry(QtCore.QRect(466, 234, 11, 11))
        self.i_Perissos.setText("")
        self.i_Perissos.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Perissos.setScaledContents(True)
        self.i_Perissos.setObjectName("i_Perissos")
        self.i_Panepistimio = QtWidgets.QLabel(self.frame_paradas)
        self.i_Panepistimio.setGeometry(QtCore.QRect(423, 506, 11, 11))
        self.i_Panepistimio.setText("")
        self.i_Panepistimio.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Panepistimio.setScaledContents(True)
        self.i_Panepistimio.setObjectName("i_Panepistimio")
        self.i_Aghios_Eleftherios = QtWidgets.QLabel(self.frame_paradas)
        self.i_Aghios_Eleftherios.setGeometry(QtCore.QRect(418, 300, 11, 11))
        self.i_Aghios_Eleftherios.setText("")
        self.i_Aghios_Eleftherios.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Aghios_Eleftherios.setScaledContents(True)
        self.i_Aghios_Eleftherios.setObjectName("i_Aghios_Eleftherios")
        self.i_Pefkakia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Pefkakia.setGeometry(QtCore.QRect(485, 210, 11, 11))
        self.i_Pefkakia.setText("")
        self.i_Pefkakia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Pefkakia.setScaledContents(True)
        self.i_Pefkakia.setObjectName("i_Pefkakia")
        self.i_Irini = QtWidgets.QLabel(self.frame_paradas)
        self.i_Irini.setGeometry(QtCore.QRect(608, 177, 11, 11))
        self.i_Irini.setText("")
        self.i_Irini.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Irini.setScaledContents(True)
        self.i_Irini.setObjectName("i_Irini")
        self.i_Pallini = QtWidgets.QLabel(self.frame_paradas)
        self.i_Pallini.setGeometry(QtCore.QRect(891, 368, 11, 11))
        self.i_Pallini.setText("")
        self.i_Pallini.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Pallini.setScaledContents(True)
        self.i_Pallini.setObjectName("i_Pallini")
        self.i_Ethniki_Amyna = QtWidgets.QLabel(self.frame_paradas)
        self.i_Ethniki_Amyna.setGeometry(QtCore.QRect(612, 407, 11, 11))
        self.i_Ethniki_Amyna.setText("")
        self.i_Ethniki_Amyna.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Ethniki_Amyna.setScaledContents(True)
        self.i_Ethniki_Amyna.setObjectName("i_Ethniki_Amyna")
        self.i_Panormou = QtWidgets.QLabel(self.frame_paradas)
        self.i_Panormou.setGeometry(QtCore.QRect(534, 439, 11, 11))
        self.i_Panormou.setText("")
        self.i_Panormou.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Panormou.setScaledContents(True)
        self.i_Panormou.setObjectName("i_Panormou")
        self.i_Egaleo = QtWidgets.QLabel(self.frame_paradas)
        self.i_Egaleo.setGeometry(QtCore.QRect(237, 449, 11, 11))
        self.i_Egaleo.setText("")
        self.i_Egaleo.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Egaleo.setScaledContents(True)
        self.i_Egaleo.setObjectName("i_Egaleo")
        self.i_Attiki = QtWidgets.QLabel(self.frame_paradas)
        self.i_Attiki.setGeometry(QtCore.QRect(382, 413, 11, 11))
        self.i_Attiki.setText("")
        self.i_Attiki.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Attiki.setScaledContents(True)
        self.i_Attiki.setObjectName("i_Attiki")
        self.i_Dafni = QtWidgets.QLabel(self.frame_paradas)
        self.i_Dafni.setGeometry(QtCore.QRect(438, 672, 11, 11))
        self.i_Dafni.setText("")
        self.i_Dafni.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Dafni.setScaledContents(True)
        self.i_Dafni.setObjectName("i_Dafni")
        self.i_Larissa_Station = QtWidgets.QLabel(self.frame_paradas)
        self.i_Larissa_Station.setGeometry(QtCore.QRect(370, 452, 11, 11))
        self.i_Larissa_Station.setText("")
        self.i_Larissa_Station.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Larissa_Station.setScaledContents(True)
        self.i_Larissa_Station.setObjectName("i_Larissa_Station")
        self.i_Evangelismos = QtWidgets.QLabel(self.frame_paradas)
        self.i_Evangelismos.setGeometry(QtCore.QRect(470, 534, 11, 11))
        self.i_Evangelismos.setText("")
        self.i_Evangelismos.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Evangelismos.setScaledContents(True)
        self.i_Evangelismos.setObjectName("i_Evangelismos")
        self.i_Katehaki = QtWidgets.QLabel(self.frame_paradas)
        self.i_Katehaki.setGeometry(QtCore.QRect(581, 439, 11, 11))
        self.i_Katehaki.setText("")
        self.i_Katehaki.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Katehaki.setScaledContents(True)
        self.i_Katehaki.setObjectName("i_Katehaki")
        self.i_Omonia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Omonia.setGeometry(QtCore.QRect(403, 487, 11, 11))
        self.i_Omonia.setText("")
        self.i_Omonia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Omonia.setScaledContents(True)
        self.i_Omonia.setObjectName("i_Omonia")
        self.i_Kerameikos = QtWidgets.QLabel(self.frame_paradas)
        self.i_Kerameikos.setGeometry(QtCore.QRect(342, 514, 11, 11))
        self.i_Kerameikos.setText("")
        self.i_Kerameikos.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Kerameikos.setScaledContents(True)
        self.i_Kerameikos.setObjectName("i_Kerameikos")
        self.i_Syntagma = QtWidgets.QLabel(self.frame_paradas)
        self.i_Syntagma.setGeometry(QtCore.QRect(431, 536, 11, 11))
        self.i_Syntagma.setText("")
        self.i_Syntagma.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Syntagma.setScaledContents(True)
        self.i_Syntagma.setObjectName("i_Syntagma")
        self.i_Maroussi = QtWidgets.QLabel(self.frame_paradas)
        self.i_Maroussi.setGeometry(QtCore.QRect(685, 106, 11, 11))
        self.i_Maroussi.setText("")
        self.i_Maroussi.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Maroussi.setScaledContents(True)
        self.i_Maroussi.setObjectName("i_Maroussi")
        self.i_Nea_Ionia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Nea_Ionia.setGeometry(QtCore.QRect(503, 185, 11, 11))
        self.i_Nea_Ionia.setText("")
        self.i_Nea_Ionia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Nea_Ionia.setScaledContents(True)
        self.i_Nea_Ionia.setObjectName("i_Nea_Ionia")
        self.i_Kato_Patissia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Kato_Patissia.setGeometry(QtCore.QRect(408, 341, 11, 11))
        self.i_Kato_Patissia.setText("")
        self.i_Kato_Patissia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Kato_Patissia.setScaledContents(True)
        self.i_Kato_Patissia.setObjectName("i_Kato_Patissia")
        self.i_Koropi = QtWidgets.QLabel(self.frame_paradas)
        self.i_Koropi.setGeometry(QtCore.QRect(950, 762, 11, 11))
        self.i_Koropi.setText("")
        self.i_Koropi.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Koropi.setScaledContents(True)
        self.i_Koropi.setObjectName("i_Koropi")
        self.i_Petralona = QtWidgets.QLabel(self.frame_paradas)
        self.i_Petralona.setGeometry(QtCore.QRect(334, 573, 11, 11))
        self.i_Petralona.setText("")
        self.i_Petralona.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Petralona.setScaledContents(True)
        self.i_Petralona.setObjectName("i_Petralona")
        self.i_Piraeus = QtWidgets.QLabel(self.frame_paradas)
        self.i_Piraeus.setGeometry(QtCore.QRect(95, 674, 11, 11))
        self.i_Piraeus.setText("")
        self.i_Piraeus.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Piraeus.setScaledContents(True)
        self.i_Piraeus.setObjectName("i_Piraeus")
        self.i_Eleonas = QtWidgets.QLabel(self.frame_paradas)
        self.i_Eleonas.setGeometry(QtCore.QRect(279, 470, 11, 11))
        self.i_Eleonas.setText("")
        self.i_Eleonas.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Eleonas.setScaledContents(True)
        self.i_Eleonas.setObjectName("i_Eleonas")
        self.i_Ambelokipi = QtWidgets.QLabel(self.frame_paradas)
        self.i_Ambelokipi.setGeometry(QtCore.QRect(512, 469, 11, 11))
        self.i_Ambelokipi.setText("")
        self.i_Ambelokipi.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Ambelokipi.setScaledContents(True)
        self.i_Ambelokipi.setObjectName("i_Ambelokipi")
        self.i_Aghios_Ioannis = QtWidgets.QLabel(self.frame_paradas)
        self.i_Aghios_Ioannis.setGeometry(QtCore.QRect(428, 634, 11, 11))
        self.i_Aghios_Ioannis.setText("")
        self.i_Aghios_Ioannis.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Aghios_Ioannis.setScaledContents(True)
        self.i_Aghios_Ioannis.setObjectName("i_Aghios_Ioannis")
        self.i_Megaro_Moussikis = QtWidgets.QLabel(self.frame_paradas)
        self.i_Megaro_Moussikis.setGeometry(QtCore.QRect(496, 513, 11, 11))
        self.i_Megaro_Moussikis.setText("")
        self.i_Megaro_Moussikis.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Megaro_Moussikis.setScaledContents(True)
        self.i_Megaro_Moussikis.setObjectName("i_Megaro_Moussikis")
        self.i_Faliro = QtWidgets.QLabel(self.frame_paradas)
        self.i_Faliro.setGeometry(QtCore.QRect(174, 693, 11, 11))
        self.i_Faliro.setText("")
        self.i_Faliro.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Faliro.setScaledContents(True)
        self.i_Faliro.setObjectName("i_Faliro")
        self.i_Kifissia = QtWidgets.QLabel(self.frame_paradas)
        self.i_Kifissia.setGeometry(QtCore.QRect(696, 13, 11, 11))
        self.i_Kifissia.setText("")
        self.i_Kifissia.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Kifissia.setScaledContents(True)
        self.i_Kifissia.setObjectName("i_Kifissia")
        self.i_Airport = QtWidgets.QLabel(self.frame_paradas)
        self.i_Airport.setGeometry(QtCore.QRect(1098, 694, 11, 11))
        self.i_Airport.setText("")
        self.i_Airport.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Airport.setScaledContents(True)
        self.i_Airport.setObjectName("i_Airport")
        self.i_Neratziotissa = QtWidgets.QLabel(self.frame_paradas)
        self.i_Neratziotissa.setGeometry(QtCore.QRect(645, 164, 11, 11))
        self.i_Neratziotissa.setText("")
        self.i_Neratziotissa.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Neratziotissa.setScaledContents(True)
        self.i_Neratziotissa.setObjectName("i_Neratziotissa")
        self.i_Moschato = QtWidgets.QLabel(self.frame_paradas)
        self.i_Moschato.setGeometry(QtCore.QRect(229, 640, 11, 11))
        self.i_Moschato.setText("")
        self.i_Moschato.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Moschato.setScaledContents(True)
        self.i_Moschato.setObjectName("i_Moschato")
        self.i_Aghios_Dimitrios = QtWidgets.QLabel(self.frame_paradas)
        self.i_Aghios_Dimitrios.setGeometry(QtCore.QRect(448, 715, 11, 11))
        self.i_Aghios_Dimitrios.setText("")
        self.i_Aghios_Dimitrios.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Aghios_Dimitrios.setScaledContents(True)
        self.i_Aghios_Dimitrios.setObjectName("i_Aghios_Dimitrios")
        self.i_Paiania_Kantza = QtWidgets.QLabel(self.frame_paradas)
        self.i_Paiania_Kantza.setGeometry(QtCore.QRect(905, 486, 11, 11))
        self.i_Paiania_Kantza.setText("")
        self.i_Paiania_Kantza.setPixmap(
            QtGui.QPixmap(resource_path("image/route_icon_image.png")))
        self.i_Paiania_Kantza.setScaledContents(True)
        self.i_Paiania_Kantza.setObjectName("i_Paiania_Kantza")
        self.Metro_Atenas = QtWidgets.QLabel(self.image_container)
        self.Metro_Atenas.setGeometry(QtCore.QRect(26, 62, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.Metro_Atenas.setFont(font)
        self.Metro_Atenas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Metro_Atenas.setObjectName("Metro_Atenas")
        self.results_container = QtWidgets.QFrame(self.centralwidget)
        self.results_container.setGeometry(QtCore.QRect(1070, 0, 341, 241))
        self.results_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.results_container.setObjectName("results_container")
        self.background_list = QtWidgets.QListView(self.results_container)
        self.background_list.setGeometry(QtCore.QRect(0, 0, 341, 251))
        self.background_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_list.setObjectName("background_list")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.results_container)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 301, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stations = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.stations.setFont(font)
        self.stations.setObjectName("stations")
        self.verticalLayout.addWidget(self.stations)
        self.distances = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.distances.setFont(font)
        self.distances.setObjectName("distances")
        self.verticalLayout.addWidget(self.distances)
        self.time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stations_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.stations_value.setFont(font)
        self.stations_value.setToolTipDuration(-2)
        self.stations_value.setText("")
        self.stations_value.setObjectName("stations_value")
        self.verticalLayout_2.addWidget(self.stations_value)
        self.distances_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.distances_value.setFont(font)
        self.distances_value.setText("")
        self.distances_value.setObjectName("distances_value")
        self.verticalLayout_2.addWidget(self.distances_value)
        self.time_value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.time_value.setFont(font)
        self.time_value.setText("")
        self.time_value.setObjectName("time_value")
        self.verticalLayout_2.addWidget(self.time_value)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lista_container = QtWidgets.QFrame(self.centralwidget)
        self.lista_container.setGeometry(QtCore.QRect(1090, 230, 320, 591))
        self.lista_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lista_container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lista_container.setLineWidth(10)
        self.lista_container.setMidLineWidth(10)
        self.lista_container.setObjectName("lista_container")
        self.stations_list = QtWidgets.QTableWidget(self.lista_container)
        self.stations_list.setGeometry(QtCore.QRect(0, 0, 321, 591))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        self.stations_list.setFont(font)
        self.stations_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stations_list.setLineWidth(0)
        self.stations_list.setProperty("showDropIndicator", True)
        self.stations_list.setShowGrid(False)
        self.stations_list.setObjectName("stations_list")
        self.stations_list.setColumnCount(2)
        self.stations_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.stations_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.stations_list.setHorizontalHeaderItem(1, item)
        self.stations_list.horizontalHeader().setVisible(True)
        self.stations_list.horizontalHeader().setCascadingSectionResizes(False)
        self.stations_list.horizontalHeader().setHighlightSections(True)
        self.stations_list.horizontalHeader().setMinimumSectionSize(30)
        self.stations_list.verticalHeader().setVisible(False)
        self.stations_list.verticalHeader().setDefaultSectionSize(30)
        self.stations_list.verticalHeader().setHighlightSections(True)
        self.frame = QtWidgets.QFrame(self.lista_container)
        self.frame.setGeometry(QtCore.QRect(0, 0, 305, 591))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ajuste = QtWidgets.QFrame(self.centralwidget)
        self.ajuste.setGeometry(QtCore.QRect(1070, 241, 21, 580))
        self.ajuste.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ajuste.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ajuste.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ajuste.setObjectName("ajuste")
        self.line_vertical = QtWidgets.QFrame(self.centralwidget)
        self.line_vertical.setGeometry(QtCore.QRect(1071, 5, 20, 810))
        self.line_vertical.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertical.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertical.setObjectName("line_vertical")
        self.line_horizontal = QtWidgets.QFrame(self.centralwidget)
        self.line_horizontal.setGeometry(QtCore.QRect(1090, 213, 310, 21))
        self.line_horizontal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horizontal.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horizontal.setObjectName("line_horizontal")
        self.results_container.raise_()
        self.image_container.raise_()
        self.lista_container.raise_()
        self.ajuste.raise_()
        self.line_vertical.raise_()
        self.line_horizontal.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1412, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.actionHelp.setFont(font)
        self.actionHelp.setShortcut("")
        self.actionHelp.setObjectName("actionHelp")
        self.action = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.action.setFont(font)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metro de Atenas"))
        self.Metro_Atenas.setText(_translate("MainWindow", "Metro de Atenas"))
        self.stations.setText(_translate("MainWindow", "Estaciones:"))
        self.distances.setText(_translate("MainWindow", "Distancia:"))
        self.time.setText(_translate("MainWindow", "Tiempo:"))
        item = self.stations_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Numero"))
        item = self.stations_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parada"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.action.setText(_translate("MainWindow", "Us"))

        self.selection_container = QtWidgets.QFrame(self.image_container)
        self.selection_container.setGeometry(QtCore.QRect(740, 0, 301, 181))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.selection_container.setFont(font)
        self.selection_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selection_container.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selection_container.setObjectName("selection_container")
        self.origin_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.origin_comboBox.setGeometry(QtCore.QRect(90, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        self.origin_comboBox.setFont(font)
        self.origin_comboBox.setObjectName("origin_comboBox")
        self.destiny_comboBox = QtWidgets.QComboBox(self.selection_container)
        self.destiny_comboBox.setGeometry(QtCore.QRect(90, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        self.destiny_comboBox.setFont(font)
        self.destiny_comboBox.setCurrentText("")
        self.destiny_comboBox.setObjectName("destiny_comboBox")
        self.destiny_icon = QtWidgets.QLabel(self.selection_container)
        self.destiny_icon.setGeometry(QtCore.QRect(10, 120, 61, 61))
        self.destiny_icon.setText("")
        self.destiny_icon.setPixmap(
            QtGui.QPixmap(resource_path("image/flag-color.png")))
        self.destiny_icon.setScaledContents(True)
        self.destiny_icon.setObjectName("destiny_icon")
        self.origin_icon = QtWidgets.QLabel(self.selection_container)
        self.origin_icon.setGeometry(QtCore.QRect(10, 30, 61, 61))
        self.origin_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.origin_icon.setText("")
        self.origin_icon.setPixmap(QtGui.QPixmap(resource_path("image/mapa-color.png")))
        self.origin_icon.setScaledContents(True)
        self.origin_icon.setObjectName("origin_icon")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
